# Generated by Django 4.1.7 on 2023-04-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('dates', models.CharField(max_length=100)),
                ('hotel', models.CharField(max_length=100)),
                ('cover', models.CharField(max_length=100)),
            ],
        ),
    ]
