# Generated by Django 4.1.7 on 2023-04-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='hotel_url',
            field=models.CharField(default='https://imgur.com/a/fm67fwT', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='cover',
            field=models.CharField(max_length=1000),
        ),
    ]
