# Generated by Django 4.1.7 on 2023-04-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_trip_hotel_url_alter_trip_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='hotel_description',
            field=models.TextField(default='Great hotel, a little expensive, but the rooms and food were amazing', max_length=400),
            preserve_default=False,
        ),
    ]
