# Generated by Django 4.1.7 on 2023-04-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant',
            new_name='restaurant_name',
        ),
    ]
